### Part 1

In [2]:
import torch
import numpy as np

In [4]:
x = torch.arange(6).reshape(3,2)

In [5]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
type(x[1,1])

torch.Tensor

In [9]:
x[:,1]

tensor([1, 3, 5])

In [11]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [12]:
x = torch.arange(10)

In [13]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x = x.reshape(2,5)

In [19]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
x = torch.arange(10)

In [24]:
x.shape

torch.Size([10])

In [25]:
z = x.view(2,5)

In [26]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
x[0] = 9999

In [28]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [38]:
x = torch.arange(10)

In [39]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x.shape

torch.Size([10])

In [41]:
# INFER what the 2nd dimension
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [42]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x.view(-1, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [68]:
a = torch.tensor([1., 2., 3.])

In [69]:
b = torch.tensor([4., 5., 6.])

In [70]:
a.dtype

torch.float32

In [71]:
b

tensor([4., 5., 6.])

In [72]:
a + b

tensor([5., 7., 9.])

In [73]:
torch.add(a,b)

tensor([5., 7., 9.])

In [74]:
a.mul(b) # == a = a * b
# a.mul_(b) == a = a * b

tensor([ 4., 10., 18.])

In [75]:
a

tensor([1., 2., 3.])

In [76]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [77]:
a

tensor([ 4., 10., 18.])

### Part 2 

In [78]:
a = torch.tensor([1., 2., 3.])

In [79]:
a * b

tensor([ 4., 10., 18.])

In [80]:
a @ b

tensor(32.)

In [81]:
a.dot(b)

tensor(32.)

In [82]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [83]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [84]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [85]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [86]:
a.shape

torch.Size([2, 3])

In [87]:
b.shape

torch.Size([3, 2])

In [88]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [89]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [90]:
x = torch.tensor([2., 3., 4., 5.])

In [92]:
x.norm()

tensor(7.3485)

In [99]:
x.numel() # number of elements

4

In [94]:
len(x)

4

In [95]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [97]:
len(a)

2

In [98]:
a.numel()

6