###  Part 1

In [4]:
import torch
import numpy as np

In [5]:
torch.__version__

'1.13.0'

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.dtype

dtype('int64')

In [10]:
type(arr)

numpy.ndarray

In [14]:
x = torch.from_numpy(arr)

In [15]:
type(x)

torch.Tensor

In [16]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [17]:
x.dtype

torch.int64

In [18]:
arr2d = np.arange(0.0, 12.0)

In [22]:
arr2d = arr2d.reshape(4,3)

In [23]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [24]:
torch.from_numpy(arr2d)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
x

tensor([1, 2, 3, 4, 5])

In [28]:
arr[0] = 99

In [29]:
arr

array([99,  2,  3,  4,  5])

In [30]:
x

tensor([99,  2,  3,  4,  5])

In [31]:
my_arr = np.arange(0, 10)

In [32]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
my_tensor = torch.tensor(my_arr)

In [34]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
my_other_tensor = torch.from_numpy(my_arr)

In [37]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
my_arr[0] = 999

In [39]:
my_arr

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [40]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
my_other_tensor

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

### Part 2 

In [42]:
new_arr = np.array([1,2,3])

In [43]:
new_arr.dtype

dtype('int64')

In [44]:
torch.tensor(new_arr).dtype

torch.int64

In [49]:
my_tensor = torch.Tensor(new_arr) # == torch.FloatTensor

In [48]:
my_tensor.dtype

torch.float32

In [58]:
torch.empty(10,10) # 아주 작은 쓸데없는 값이 할당됨

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
torch.zeros(4,3, dtype=torch.int64) 

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [60]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [62]:
torch.arange(0, 18, 2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [65]:
torch.linspace(0, 18, 12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [66]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [67]:
my_tensor = torch.tensor([1,2,3])

In [68]:
my_tensor.dtype

torch.int64

In [70]:
my_tensor = my_tensor.type(torch.int32)

In [71]:
my_tensor.dtype

torch.int32

In [72]:
torch.rand(4,3)

tensor([[0.2370, 0.9335, 0.0709],
        [0.3919, 0.5660, 0.4186],
        [0.1745, 0.1529, 0.4873],
        [0.1967, 0.9936, 0.7676]])

In [73]:
torch.randn(4,3)

tensor([[ 0.1161, -0.6903,  0.6464],
        [ 0.0232,  0.7039,  2.0031],
        [ 0.1568,  1.1343, -0.0890],
        [ 0.0770, -0.2537,  2.9317]])

In [76]:
torch.randint(low=0, high=10, size=(5,5))

tensor([[5, 4, 6, 9, 2],
        [2, 8, 9, 2, 6],
        [9, 6, 5, 2, 8],
        [7, 4, 4, 9, 3],
        [4, 5, 2, 1, 6]])

In [77]:
x = torch.zeros(2,5)

In [78]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [79]:
x.shape

torch.Size([2, 5])

In [80]:
torch.rand_like(x)

tensor([[0.3784, 0.5600, 0.8813, 0.1215, 0.6669],
        [0.7143, 0.8705, 0.5185, 0.7242, 0.2129]])

In [81]:
torch.randn_like(x)

tensor([[-1.2778,  0.0827, -2.8097, -0.1977, -0.2042],
        [-0.7135,  0.6230,  1.8425, -0.4193, -1.9621]])

In [82]:
torch.randint_like(x, low=0, high=10)

tensor([[6., 0., 7., 1., 6.],
        [5., 3., 7., 7., 7.]])

In [88]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [89]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [90]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])